version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Babul123
      MYSQL_DATABASE: college
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  java-app:
    image: myapp:1.0  # Replace with your actual Java application image
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/college
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Babul123
    ports:
      - "9191:9191"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
